// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using another_test.Data;

namespace another_test.Migrations
{
    [DbContext(typeof(another_testContext))]
    partial class another_testContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("techSupport.Model.SupportReq", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpired")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromWhoID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SupportReq");
                });

            modelBuilder.Entity("techSupport.Model.SupportTakeReq", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ReqStatus")
                        .HasColumnType("int");

                    b.Property<int>("SupportReqID")
                        .HasColumnType("int");

                    b.Property<int>("SupporterPresonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SupportReqID");

                    b.ToTable("SupportTakeReq");
                });

            modelBuilder.Entity("techSupport.Model.SupportTakeReq", b =>
                {
                    b.HasOne("techSupport.Model.SupportReq", "SupportReq")
                        .WithMany("SupportTakeReqs")
                        .HasForeignKey("SupportReqID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
